# Generated by Django 6.1 on 2026-09-01 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='content',
            field=models.TextField(default='no messages'),
            preserve_default=False,
        ),
    ]
